sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t isji/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true isji/react-test npm run test -- --coverage

after_success:
  - docker build -t isji/multi-client ./client
  - docker build -t isji/multi-nginx ./nginx
  - docker build -t isji/multi-server ./server
  - docker build -t isji/multi-worker ./worker
  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push isji/multi-client
  - docker push isji/multi-nginx
  - docker push isji/multi-server
  - docker push isji/multi-worker

deploy: 
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-832480472331
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
